### ISSUE TITLE
dont work anymore chrome 73

### ISSUE THREAD

**Issue by malohtie** [vitalets/webrtc-ips#3]
![image](https://user-images.githubusercontent.com/20033279/57448302-8bca1800-7248-11e9-92ee-d1808a8a3379.png)

**Comment by vitalets** [comment]
Works in my Chrome 74 (osx):
![image](https://user-images.githubusercontent.com/1473072/57938885-cb8ca180-78d1-11e9-9455-503a5fecd719.png)

Could you re-check and provide full user agent?

**Comment by malohtie** [comment]
here you go
![image](https://user-images.githubusercontent.com/20033279/57939187-4d240580-78b9-11e9-8cc7-964f086cc639.png)

**Comment by vitalets** [comment]
Thanks!
I found [this discussion](https://groups.google.com/forum/#!msg/discuss-webrtc/l0gc3RjBhc0/FsMqOlOSBwAJ) where hiding IP is mentioned:

> mDNS for local ICE candidates
> With this feature, host IPs will no longer directly be exposed by the RTCPeerConnection API, increasing privacy. Host candidates will only indirectly be exposed through a randomly generated mDNS hostname. Purpose and mechanisms used are described in this spec: https://tools.ietf.org/html/draft-ietf-rtcweb-mdns-ice-candidates-02

**Comment by malohtie** [comment]
Great so i think in future they will be no leak of local ip

**Comment by vitalets** [comment]
Now special flags are required to allow browser to share local IPs. 
With flags set library is working. See https://github.com/vitalets/webrtc-ips/pull/4#issuecomment-771500859
